services:
  webserver:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./frontend/public:/usr/share/nginx/html:ro
      - ./.develop/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - vet-network
    depends_on:
      - php-fpm

  php-fpm:
    build: ./backend
    container_name: php-fmp
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/var/www/html
    networks:
      - vet-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vet_db
      MYSQL_USER: vet_user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./.develop/database/:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    networks:
      - vet-network

  adminer:
    image: adminer:4.8.1
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: dracula
    networks:
      - vet-network
    depends_on:
      - db

networks:
  vet-network:
    driver: bridge

volumes:
  mysql_data:
