services:
  webserver:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro 
      # ./backend:/var/www/html
      - ./.develop/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - vet-network
    depends_on:
      - php-fpm

  php-fpm:
    build: ./backend 
    container_name: laravel
    env_file:
      - ./backend/.env
    image: php:8.4.13-fpm
    volumes: 
      - ./backend:/app
      # ./backend:/var/www/html
    networks: 
      - vet-network
    depends_on:
      - db

  db:
    image: mysql:mysql:9.5.0-oraclelinux9
    environment: 
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vet_db
      MYSQL_USER: vet_user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./.develop/database/001_init_dump.sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - vet-network

  adminer:
    image: adminer:4.8.1
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: dracula
    networks:
      - vet-network
    depends_on:
      - db

networks:
  quiz-network:
    driver: bridge

volumes:
  mysql_data: